### ISSUE TITLE
Uploader JSON Errors

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#588]
The Video Uploader console app is still getting these:

```
[10:29:11 INF] SyncAsync Started
[10:29:15 ERR] Error occurred The JSON value could not be converted to DevBetterWeb.Vimeo.Models.Files. Path: $.files | LineNumber: 0 | BytePositionInLine: 10419.    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at DevBetter.JsonExtensions.Converters.MissingMemberConverter.GetObjectValue(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at DevBetter.JsonExtensions.Converters.MissingMemberConverter.ExtractValue(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at DevBetter.JsonExtensions.Converters.MissingMemberConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Ardalis.ApiClient.HttpResponse`1..ctor(HttpResponseMessage result)
   at Ardalis.ApiClient.HttpResponse`1.FromHttpResponseMessage(HttpResponseMessage result)
   at Ardalis.ApiClient.HttpService.HttpGetAsync[T](String uri, Dictionary`2 query)
   at DevBetterWeb.Vimeo.Services.VideoServices.GetAllVideosService.ExecuteAsync(GetAllVideosRequest request, CancellationToken cancellationToken) in C:\dev\GitHub\devbetterweb\src\DevBetterWeb.Vimeo\Services\VideoServices\GetAllVideosService.cs:line 54  System.Text.Json
[10:29:26 INF] Found 45 videos in toupload.
```

**Comment by ShadyNagy** [comment]
Fixed.
